version: "2"
run:
  build-tags:
    - remote
    - exclude_graphdriver_btrfs
    - btrfs_noversion
    - exclude_graphdriver_devicemapper
    - containers_image_openpgp
linters:
  enable:
    - bodyclose
    - copyloopvar
    - dogsled
    - dupl
    - goconst
    - gocritic
    - gosec
    - misspell
    - prealloc
    - unconvert
  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-tags:
        - diagnostic
        - performance
        - style
    gosec:
      excludes:
        - G104
    govet:
      enable-all: true
    misspell:
      locale: US
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - dupl
          - goconst
          - gosec
        path: _test\.go
      - linters:
          - govet
        text: 'shadow: declaration of "err"'
      - linters:
          - errcheck
        path: _test\.go
        text: client.Remove
      - linters:
          - govet
        path: _test\.go
        text: fieldalignment
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 50
  max-same-issues: 10
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
